/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as AppTutorRouteImport } from './routes/_app/tutor'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPlaygroundRouteImport } from './routes/_app/playground'
import { Route as AppInstructorRouteImport } from './routes/_app/instructor'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCommunityRouteImport } from './routes/_app/community'
import { Route as AppCertificatesRouteImport } from './routes/_app/certificates'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppCoursesIndexRouteImport } from './routes/_app/courses.index'
import { Route as AppCoursesSlugRouteImport } from './routes/_app/courses.$slug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTutorRoute = AppTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaygroundRoute = AppPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AppRoute,
} as any)
const AppInstructorRoute = AppInstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesRoute = AppCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesSlugRoute = AppCoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/certificates': typeof AppCertificatesRoute
  '/community': typeof AppCommunityRoute
  '/dashboard': typeof AppDashboardRoute
  '/instructor': typeof AppInstructorRoute
  '/playground': typeof AppPlaygroundRoute
  '/profile': typeof AppProfileRoute
  '/tutor': typeof AppTutorRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/courses/$slug': typeof AppCoursesSlugRoute
  '/courses/': typeof AppCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/certificates': typeof AppCertificatesRoute
  '/community': typeof AppCommunityRoute
  '/dashboard': typeof AppDashboardRoute
  '/instructor': typeof AppInstructorRoute
  '/playground': typeof AppPlaygroundRoute
  '/profile': typeof AppProfileRoute
  '/tutor': typeof AppTutorRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/courses/$slug': typeof AppCoursesSlugRoute
  '/courses': typeof AppCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/certificates': typeof AppCertificatesRoute
  '/_app/community': typeof AppCommunityRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/instructor': typeof AppInstructorRoute
  '/_app/playground': typeof AppPlaygroundRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/tutor': typeof AppTutorRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/_app/courses/$slug': typeof AppCoursesSlugRoute
  '/_app/courses/': typeof AppCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/certificates'
    | '/community'
    | '/dashboard'
    | '/instructor'
    | '/playground'
    | '/profile'
    | '/tutor'
    | '/verify/$code'
    | '/courses/$slug'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/certificates'
    | '/community'
    | '/dashboard'
    | '/instructor'
    | '/playground'
    | '/profile'
    | '/tutor'
    | '/verify/$code'
    | '/courses/$slug'
    | '/courses'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_app/admin'
    | '/_app/certificates'
    | '/_app/community'
    | '/_app/dashboard'
    | '/_app/instructor'
    | '/_app/playground'
    | '/_app/profile'
    | '/_app/tutor'
    | '/verify/$code'
    | '/_app/courses/$slug'
    | '/_app/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tutor': {
      id: '/_app/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AppTutorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playground': {
      id: '/_app/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof AppPlaygroundRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/instructor': {
      id: '/_app/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof AppInstructorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/certificates': {
      id: '/_app/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AppCertificatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/': {
      id: '/_app/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/$slug': {
      id: '/_app/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof AppCoursesSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCertificatesRoute: typeof AppCertificatesRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInstructorRoute: typeof AppInstructorRoute
  AppPlaygroundRoute: typeof AppPlaygroundRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTutorRoute: typeof AppTutorRoute
  AppCoursesSlugRoute: typeof AppCoursesSlugRoute
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCertificatesRoute: AppCertificatesRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInstructorRoute: AppInstructorRoute,
  AppPlaygroundRoute: AppPlaygroundRoute,
  AppProfileRoute: AppProfileRoute,
  AppTutorRoute: AppTutorRoute,
  AppCoursesSlugRoute: AppCoursesSlugRoute,
  AppCoursesIndexRoute: AppCoursesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyCodeRoute: VerifyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
